using '../main.bicep'

param location = 'centralus'
param environmentName = 'prod'
param appName = 'dddsocial'
param keyVaultName = 'kv-jdpeckham'
param dnsZoneName = 'azure.jdpeckham.com'
param webHostName = 'dddsocial.azure.jdpeckham.com'
param cosmosAccountName = 'cosmos-cleansocial-prod'
param githubRepositoryOwner = 'jpeckham'
param githubRepositoryName = 'domain-driven-design-csharp'
param githubBranch = 'main'
param githubEnvironmentName = 'production'
param staticWebAppSku = 'Free'
